#Das Modul Posix wird benötig.
# in der shell installieren
# ansible-galaxy collection install ansible.posix
---
- name: "copy ssh"
  ansible.posix.authorized_key:
      user: root
      state: present
      key: "{{ lookup('file', '{{ item }}') }}"
  with_items:
    - "{{ ssh_key_list }}"
  register: ssh_key_installed

- name: Schlüssel angelget?
  debug:
    msg:
     - "Schlüsselanlegestatus : {{ ssh_key_installed }}"

- name: "Disable root login per password"
  raw: sed -i 's/PermitRootLogin yes/#PermitRootLogin no/g' /etc/ssh/sshd_config
  #Dieses ruft den handler mit dem namen "restart ssh" im Verzeichnis handlers/main.yml auf. 
  notify: 
    - restart ssh